[project]
name = "aug-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=45.0.4",
    "flask>=3.1.1",
    "gunicorn>=23.0.0",
    "keyring>=25.6.0",
    "requests>=2.32.4",
]
