name: Upload File to GitHub Artifacts
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REPO_NAME: "augweb"
  REF_NAME: "v3"

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.13'
        requirements: './requirements.txt'
        spec: './db_manager.py'
        upload_exe_with_name: 'My executable'
        options: --onefile,--hidden-import=datebase, --name "My App", --windowed

    
    - name: Print
      run: |
        ls dist
        echo $(basename "$(pwd)")
        echo $GITHUB_EVENT_PATH
        EVENT_DATA=$(cat $GITHUB_EVENT_PATH)
        echo $EVENT_DATA | jq .

    - name: Upload a file to GitHub Artifacts
      uses: actions/upload-artifact@main
      with:
        name: my-artifact
        path: ./dist
