name: Multi-Platform PyInstaller Build

on:
  push:
    tags:
      - 'v*'  # 触发标签格式为 v1.0.0 这样的版本号

jobs:
  # --- Linux Builds ---
  build-linux-amd64:
    runs-on: ubuntu-latest # GitHub's default Ubuntu runner is amd64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Choose your Python version
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build PyInstaller executable (Linux AMD64)
        run: pyinstaller --onefile --name=dbmanager --clean --noconfirm --hidden-import=datebase db_manager.py
      - name: Rename executable
        run: mv dist/dbmanager dist/dbmanager-linux-amd64
      - name: Upload artifact (Linux AMD64)
        uses: actions/upload-artifact@v4
        with:
          name: dbmanager-linux-amd64
          path: dist/dbmanager-linux-amd64


  build-linux-amd64-debian:
    runs-on: ubuntu-latest # You'll need an ARM64 runner or use QEMU/Docker buildx
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Option 1: Use an ARM64 runner if available (e.g., self-hosted or specific GitHub runner)
      # Option 2: Use Docker Buildx with emulation (more complex, see below)
      # For simplicity, if using GitHub-hosted runners, you might use 'ubuntu-latest' and rely on Docker buildx
      # Or if self-hosted, specify an 'arm64' label.
      # For now, let's assume `runs-on: ubuntu-latest` and we'll use Docker buildx below.
      - name: Set up QEMU ( Linux AMD64 Debian runner)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for Linux AMD64 Debian
        run: |
          docker buildx build --platform linux/amd64 -t pyinstaller-amd64-builder -f Dockerfile.debian . --load
      - name: Run container and retrieve executable (Linux AMD64 Debian)
        run: |
          CONTAINER_ID=$(docker create pyinstaller-amd64-builder)
          docker cp $CONTAINER_ID:/app/dist/dbmanager ./dbmanager-linux-amd64-debian
          docker rm $CONTAINER_ID
      - name: Upload artifact (Linux AMD64 Debian)
        uses: actions/upload-artifact@v4
        with:
          name: dbmanager-linux-amd64-debian
          path: dbmanager-linux-amd64-debian


  build-linux-arm64:
    runs-on: ubuntu-latest # You'll need an ARM64 runner or use QEMU/Docker buildx
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Option 1: Use an ARM64 runner if available (e.g., self-hosted or specific GitHub runner)
      # Option 2: Use Docker Buildx with emulation (more complex, see below)
      # For simplicity, if using GitHub-hosted runners, you might use 'ubuntu-latest' and rely on Docker buildx
      # Or if self-hosted, specify an 'arm64' label.
      # For now, let's assume `runs-on: ubuntu-latest` and we'll use Docker buildx below.
      - name: Set up QEMU (for ARM64 emulation on AMD64 runner)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for Linux ARM64
        run: |
          docker buildx build --platform linux/arm64/v8 -t pyinstaller-arm64-builder -f Dockerfile.arm64 . --load
      - name: Run container and retrieve executable (Linux ARM64)
        run: |
          CONTAINER_ID=$(docker create pyinstaller-arm64-builder)
          docker cp $CONTAINER_ID:/app/dist/dbmanager ./dbmanager-linux-arm64
          docker rm $CONTAINER_ID
      - name: Upload artifact (Linux ARM64)
        uses: actions/upload-artifact@v4
        with:
          name: dbmanager-linux-arm64
          path: dbmanager-linux-arm64

  # --- Windows Build ---
  build-windows:
    runs-on: windows-latest # GitHub's Windows runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build PyInstaller executable (Windows)
        run: pyinstaller --onefile --name=dbmanager --clean --noconfirm --hidden-import=datebase db_manager.py
      - name: Rename executable
        run: Move-Item dist/dbmanager.exe dist/dbmanager-windows.exe # PowerShell syntax
      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: dbmanager-windows
          path: dist/dbmanager-windows.exe

  # ... (previous jobs) ...

  build-macos-arm64:
    runs-on: macos-latest # GitHub's macOS runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Or your desired Python version
      - name: Install dependencies
        run: pip install pyinstaller -r requirements.txt
      - name: Build PyInstaller executable (macOS)
        # Corrected line: 'pyinstaller' instead of 'ppyinstaller'
        run: pyinstaller --onefile --name=dbmanager --clean --noconfirm --hidden-import=datebase db_manager.py
      - name: Rename executable
        # Adjust as per your actual output path if different
        run: mv dist/dbmanager dist/dbmanager-macos
      - name: Upload artifact (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: dbmanager-macos-arm64
          path: dist/dbmanager-macos

  build-macos-Intel:
    runs-on: macos-13 # GitHub's macOS runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Or your desired Python version
      - name: Install dependencies
        run: pip install pyinstaller -r requirements.txt
      - name: Build PyInstaller executable (macOS)
        # Corrected line: 'pyinstaller' instead of 'ppyinstaller'
        run: pyinstaller --onefile --name=dbmanager --clean --noconfirm --hidden-import=datebase db_manager.py
      - name: Rename executable
        # Adjust as per your actual output path if different
        run: mv dist/dbmanager dist/dbmanager-macos
      - name: Upload artifact (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: dbmanager-macos-Intel
          path: dist/dbmanager-macos

  # 在所有其他 jobs 后面添加
  create-release:
    needs: [build-linux-amd64, build-linux-amd64-debian, build-linux-arm64, build-windows, build-macos-arm64, build-macos-Intel]
    runs-on: ubuntu-latest
    # 只在推送标签时运行
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/dbmanager-linux-amd64/*
            artifacts/dbmanager-linux-amd64-debian/*
            artifacts/dbmanager-linux-arm64/*
            artifacts/dbmanager-windows/*
            artifacts/dbmanager-macos-arm64/*
            artifacts/dbmanager-macos-Intel/*
          draft: false
          prerelease: false
          generate_release_notes: true

